from __future__ import annotations

from typing import Protocol


class StorageProvider(Protocol):
    def save(self, key: str, data: bytes, content_type: str = "application/octet-stream") -> str: ...

    def load(self, key: str) -> bytes: ...

    def exists(self, key: str) -> bool: ...

    def list_prefix(self, prefix: str) -> list[str]: ...

    def get_url(self, key: str) -> str: ...
